import type { ComponentType, SVGProps } from "react";
import {
  Allergies, AutoimmuneDisease, BackPain, Chills, CoughingAlt, Deaf, Diarrhea, Headache,
  IntestinalPain, LowVision, Overweight, Pneumonia, Sweating, Underweight, Vomiting, Arm,
  Bladder, BloodCells, BloodDrop, Body, CellNuclei, Dna, Ear, Eye,
  Foot, Gallbladder, HeartOrgan, Joints, Kidneys, Leg, Liver, Lungs,
  Mouth, Neurology, Nose, Pancreas, Skeleton, Skull, Spine, Spleen,
  Stomach, Tissue, Tooth, Tumour, BloodPressureMonitor, DiabetesMeasure, Fever, Stethoscope,
  ThermometerDigital, OxygenTank, Ventilator, Xray, Coughing, Crying, Dizzy, Expectorate,
  FeverEmotions, Nauseous, Sleepy, SweatingEmotions, Tongue, Woozy, Cardiogram, Heartbeat,
  MentalHealth, Poison, Smoking, Virus, Symptom, Antibody, Enzyme, FemaleReproductiveSystem,
  PenisAlt, Prostate, VaginaAlt, CervicalCancer, Gonorrhea, Ribbon, Tb, Vih,
  Angry, Bandaged, Calm, Confused, Happy, LoudlyCrying, Masked, Measles,
  Nervous, Neutral, NotOk, Ok, Sad, ContactLenses, CpapMachine, CpapMasks,
  CpapTubes, Defibrillator, Ecmo, Hospitalized, Inpatient, InfusionPump, IntravenousBag, Llin,
  Microscope, Observation, Staples, Stitches, Syringe, TestTubes, Wheelchair, WheelchairAlt,
  Biopsy, Diabetes, Doctor, HealthWorker, Pregnant, WaterSanitation, Hospital, EmergencyPost,
  Respirator, Biomarker, Death, Diagnostics, Hazardous, Health, Heart, HeartCardiogram,
  HomeQuarantine, Hospice, Outbreak, PalliativeCare, Pharmacy, RiskAnalysis, SmokingCessation, VirusAlt,
  Ambulance, Mosquito, Medicines, Pill1, Pills2, Pills3, Pills4, Nutrition,
  SugarFree, UnhealthyFood, RunningWater, Walking, WalkSupported, Running,
} from "healthicons-react/outline-24px";

export type HealthIconComponent = ComponentType<SVGProps<SVGSVGElement>>;

export const HEALTH_ICON_NAMES = [
  "Allergies",
  "AutoimmuneDisease",
  "BackPain",
  "Chills",
  "CoughingAlt",
  "Deaf",
  "Diarrhea",
  "Headache",
  "IntestinalPain",
  "LowVision",
  "Overweight",
  "Pneumonia",
  "Sweating",
  "Underweight",
  "Vomiting",
  "Arm",
  "Bladder",
  "BloodCells",
  "BloodDrop",
  "Body",
  "CellNuclei",
  "Dna",
  "Ear",
  "Eye",
  "Foot",
  "Gallbladder",
  "HeartOrgan",
  "Joints",
  "Kidneys",
  "Leg",
  "Liver",
  "Lungs",
  "Mouth",
  "Neurology",
  "Nose",
  "Pancreas",
  "Skeleton",
  "Skull",
  "Spine",
  "Spleen",
  "Stomach",
  "Tissue",
  "Tooth",
  "Tumour",
  "BloodPressureMonitor",
  "DiabetesMeasure",
  "Fever",
  "Stethoscope",
  "ThermometerDigital",
  "OxygenTank",
  "Ventilator",
  "Xray",
  "Coughing",
  "Crying",
  "Dizzy",
  "Expectorate",
  "FeverEmotions",
  "Nauseous",
  "Sleepy",
  "SweatingEmotions",
  "Tongue",
  "Woozy",
  "Cardiogram",
  "Heartbeat",
  "MentalHealth",
  "Poison",
  "Smoking",
  "Virus",
  "Symptom",
  "Antibody",
  "Enzyme",
  "FemaleReproductiveSystem",
  "PenisAlt",
  "Prostate",
  "VaginaAlt",
  "CervicalCancer",
  "Gonorrhea",
  "Ribbon",
  "Tb",
  "Vih",
  "Angry",
  "Bandaged",
  "Calm",
  "Confused",
  "Happy",
  "LoudlyCrying",
  "Masked",
  "Measles",
  "Nervous",
  "Neutral",
  "NotOk",
  "Ok",
  "Sad",
  "ContactLenses",
  "CpapMachine",
  "CpapMasks",
  "CpapTubes",
  "Defibrillator",
  "Ecmo",
  "Hospitalized",
  "Inpatient",
  "InfusionPump",
  "IntravenousBag",
  "Llin",
  "Microscope",
  "Observation",
  "Staples",
  "Stitches",
  "Syringe",
  "TestTubes",
  "Wheelchair",
  "WheelchairAlt",
  "Biopsy",
  "Diabetes",
  "Doctor",
  "HealthWorker",
  "Pregnant",
  "WaterSanitation",
  "Hospital",
  "EmergencyPost",
  "Respirator",
  "Biomarker",
  "Death",
  "Diagnostics",
  "Hazardous",
  "Health",
  "Heart",
  "HeartCardiogram",
  "HomeQuarantine",
  "Hospice",
  "Outbreak",
  "PalliativeCare",
  "Pharmacy",
  "RiskAnalysis",
  "SmokingCessation",
  "VirusAlt",
  "Ambulance",
  "Mosquito",
  "Medicines",
  "Pill1",
  "Pills2",
  "Pills3",
  "Pills4",
  "Nutrition",
  "SugarFree",
  "UnhealthyFood",
  "RunningWater",
  "Walking",
  "WalkSupported",
  "Running"
] as const;

export const HEALTH_ICONS: Record<string, HealthIconComponent> = {
  Allergies, AutoimmuneDisease, BackPain, Chills, CoughingAlt, Deaf, Diarrhea, Headache,
  IntestinalPain, LowVision, Overweight, Pneumonia, Sweating, Underweight, Vomiting, Arm,
  Bladder, BloodCells, BloodDrop, Body, CellNuclei, Dna, Ear, Eye,
  Foot, Gallbladder, HeartOrgan, Joints, Kidneys, Leg, Liver, Lungs,
  Mouth, Neurology, Nose, Pancreas, Skeleton, Skull, Spine, Spleen,
  Stomach, Tissue, Tooth, Tumour, BloodPressureMonitor, DiabetesMeasure, Fever, Stethoscope,
  ThermometerDigital, OxygenTank, Ventilator, Xray, Coughing, Crying, Dizzy, Expectorate,
  FeverEmotions, Nauseous, Sleepy, SweatingEmotions, Tongue, Woozy, Cardiogram, Heartbeat,
  MentalHealth, Poison, Smoking, Virus, Symptom, Antibody, Enzyme, FemaleReproductiveSystem,
  PenisAlt, Prostate, VaginaAlt, CervicalCancer, Gonorrhea, Ribbon, Tb, Vih,
  Angry, Bandaged, Calm, Confused, Happy, LoudlyCrying, Masked, Measles,
  Nervous, Neutral, NotOk, Ok, Sad, ContactLenses, CpapMachine, CpapMasks,
  CpapTubes, Defibrillator, Ecmo, Hospitalized, Inpatient, InfusionPump, IntravenousBag, Llin,
  Microscope, Observation, Staples, Stitches, Syringe, TestTubes, Wheelchair, WheelchairAlt,
  Biopsy, Diabetes, Doctor, HealthWorker, Pregnant, WaterSanitation, Hospital, EmergencyPost,
  Respirator, Biomarker, Death, Diagnostics, Hazardous, Health, Heart, HeartCardiogram,
  HomeQuarantine, Hospice, Outbreak, PalliativeCare, Pharmacy, RiskAnalysis, SmokingCessation, VirusAlt,
  Ambulance, Mosquito, Medicines, Pill1, Pills2, Pills3, Pills4, Nutrition,
  SugarFree, UnhealthyFood, RunningWater, Walking, WalkSupported, Running,
};

