import {
  Activity, Stethoscope, Heart, HeartPulse, HeartHandshake, Newspaper, Pill, Syringe, Thermometer,
  ThermometerSun, ThermometerSnowflake, Brain, Bone, Eye, EyeOff, Ear, Baby,
  Ambulance, Hospital, Droplet, Droplets, Wind, Zap, AlertTriangle, ShieldAlert,
  ShieldCheck, ShieldPlus, Flame, Bug, Microscope, TestTube, TestTube2, FlaskConical,
  Waves, Sun, Moon, CloudRain, Snowflake, Utensils, Apple, Salad,
  Dumbbell, Bed, Frown, Smile, Meh, Users, User, UserRound,
  Accessibility, Watch, Clock, Calendar, ClipboardList, FileText, Folder, FolderOpen,
  Tag, Star, Siren, LifeBuoy, Cross, Hand, Footprints, PersonStanding,
  ScanFace, BicepsFlexed, Angry, Annoyed, CircleAlert, CircleCheck, CircleHelp, CircleX,
  BadgeAlert, OctagonAlert, Radiation, Biohazard, Dna, Atom, Tablets, Cannabis,
  Bandage, BriefcaseMedical, CirclePlus, SquareActivity, ChartNoAxesCombined, Weight, Gauge, CircleGauge,
  Battery, BatteryLow, AlarmClock, Timer, Cigarette, CigaretteOff, GlassWater, CupSoda,
  Soup, Fish, Beef, Egg, Milk, Wheat, Cherry, Grape,
  Citrus, Carrot, Banana, Bike, Bath, ShowerHead, SoapDispenserDroplet, Shield,
  VenetianMask, Speech, MessageCircle, Headphones, Volume2, VolumeX, HandHeart, HandHelping,
  BedSingle, BedDouble, Move, MoveUp, MoveDown, MoveLeft, MoveRight, ArrowUpDown,
  RotateCcw, RefreshCcw, Worm, Rat, BugOff, ShieldX, ShieldMinus, BadgePlus,
  BadgeMinus, CircleMinus, HeartCrack, HeartOff, BrainCircuit, BrainCog, Scan, ScanEye,
  ScanHeart, ScanLine, ScanSearch, AudioWaveform, ChartSpline, TrendingUp, TrendingDown, CloudFog,
  Cloudy, EyeClosed, EarOff, MicVocal, MicOff, UtensilsCrossed, Ban, DropletOff,
  CircleSlash, Fingerprint, Sparkles, SunDim, SunSnow, CloudLightning, CloudSun, CircleDot,
  CircleDotDashed, MoveVertical, MoveHorizontal, Webcam, Telescope, SearchCheck, SearchX, Vegan,
  Dessert, Cookie, Coffee, BeerOff, WineOff, PillBottle, HandPlatter, HandMetal,
  HandFist, ThumbsDown, ThumbsUp, CircleOff, OctagonX,
  type LucideIcon,
} from "lucide-react";

export const LUCIDE_ICON_NAMES = [
  "Activity",
  "Stethoscope",
  "Heart",
  "HeartPulse",
  "HeartHandshake",
  "Newspaper",
  "Pill",
  "Syringe",
  "Thermometer",
  "ThermometerSun",
  "ThermometerSnowflake",
  "Brain",
  "Bone",
  "Eye",
  "EyeOff",
  "Ear",
  "Baby",
  "Ambulance",
  "Hospital",
  "Droplet",
  "Droplets",
  "Wind",
  "Zap",
  "AlertTriangle",
  "ShieldAlert",
  "ShieldCheck",
  "ShieldPlus",
  "Flame",
  "Bug",
  "Microscope",
  "TestTube",
  "TestTube2",
  "FlaskConical",
  "Waves",
  "Sun",
  "Moon",
  "CloudRain",
  "Snowflake",
  "Utensils",
  "Apple",
  "Salad",
  "Dumbbell",
  "Bed",
  "Frown",
  "Smile",
  "Meh",
  "Users",
  "User",
  "UserRound",
  "Accessibility",
  "Watch",
  "Clock",
  "Calendar",
  "ClipboardList",
  "FileText",
  "Folder",
  "FolderOpen",
  "Tag",
  "Star",
  "Siren",
  "LifeBuoy",
  "Cross",
  "Hand",
  "Footprints",
  "PersonStanding",
  "ScanFace",
  "BicepsFlexed",
  "Angry",
  "Annoyed",
  "CircleAlert",
  "CircleCheck",
  "CircleHelp",
  "CircleX",
  "BadgeAlert",
  "OctagonAlert",
  "Radiation",
  "Biohazard",
  "Dna",
  "Atom",
  "Tablets",
  "Cannabis",
  "Bandage",
  "BriefcaseMedical",
  "CirclePlus",
  "SquareActivity",
  "ChartNoAxesCombined",
  "Weight",
  "Gauge",
  "CircleGauge",
  "Battery",
  "BatteryLow",
  "AlarmClock",
  "Timer",
  "Cigarette",
  "CigaretteOff",
  "GlassWater",
  "CupSoda",
  "Soup",
  "Fish",
  "Beef",
  "Egg",
  "Milk",
  "Wheat",
  "Cherry",
  "Grape",
  "Citrus",
  "Carrot",
  "Banana",
  "Bike",
  "Bath",
  "ShowerHead",
  "SoapDispenserDroplet",
  "Shield",
  "VenetianMask",
  "Speech",
  "MessageCircle",
  "Headphones",
  "Volume2",
  "VolumeX",
  "HandHeart",
  "HandHelping",
  "BedSingle",
  "BedDouble",
  "Move",
  "MoveUp",
  "MoveDown",
  "MoveLeft",
  "MoveRight",
  "ArrowUpDown",
  "RotateCcw",
  "RefreshCcw",
  "Worm",
  "Rat",
  "BugOff",
  "ShieldX",
  "ShieldMinus",
  "BadgePlus",
  "BadgeMinus",
  "CircleMinus",
  "HeartCrack",
  "HeartOff",
  "BrainCircuit",
  "BrainCog",
  "Scan",
  "ScanEye",
  "ScanHeart",
  "ScanLine",
  "ScanSearch",
  "AudioWaveform",
  "ChartSpline",
  "TrendingUp",
  "TrendingDown",
  "CloudFog",
  "Cloudy",
  "EyeClosed",
  "EarOff",
  "MicVocal",
  "MicOff",
  "UtensilsCrossed",
  "Ban",
  "DropletOff",
  "CircleSlash",
  "Fingerprint",
  "Sparkles",
  "SunDim",
  "SunSnow",
  "CloudLightning",
  "CloudSun",
  "CircleDot",
  "CircleDotDashed",
  "MoveVertical",
  "MoveHorizontal",
  "Webcam",
  "Telescope",
  "SearchCheck",
  "SearchX",
  "Vegan",
  "Dessert",
  "Cookie",
  "Coffee",
  "BeerOff",
  "WineOff",
  "PillBottle",
  "HandPlatter",
  "HandMetal",
  "HandFist",
  "ThumbsDown",
  "ThumbsUp",
  "CircleOff",
  "OctagonX"
] as const;

export const LUCIDE_ICONS: Record<string, LucideIcon> = {
  Activity, Stethoscope, Heart, HeartPulse, HeartHandshake, Newspaper, Pill, Syringe, Thermometer,
  ThermometerSun, ThermometerSnowflake, Brain, Bone, Eye, EyeOff, Ear, Baby,
  Ambulance, Hospital, Droplet, Droplets, Wind, Zap, AlertTriangle, ShieldAlert,
  ShieldCheck, ShieldPlus, Flame, Bug, Microscope, TestTube, TestTube2, FlaskConical,
  Waves, Sun, Moon, CloudRain, Snowflake, Utensils, Apple, Salad,
  Dumbbell, Bed, Frown, Smile, Meh, Users, User, UserRound,
  Accessibility, Watch, Clock, Calendar, ClipboardList, FileText, Folder, FolderOpen,
  Tag, Star, Siren, LifeBuoy, Cross, Hand, Footprints, PersonStanding,
  ScanFace, BicepsFlexed, Angry, Annoyed, CircleAlert, CircleCheck, CircleHelp, CircleX,
  BadgeAlert, OctagonAlert, Radiation, Biohazard, Dna, Atom, Tablets, Cannabis,
  Bandage, BriefcaseMedical, CirclePlus, SquareActivity, ChartNoAxesCombined, Weight, Gauge, CircleGauge,
  Battery, BatteryLow, AlarmClock, Timer, Cigarette, CigaretteOff, GlassWater, CupSoda,
  Soup, Fish, Beef, Egg, Milk, Wheat, Cherry, Grape,
  Citrus, Carrot, Banana, Bike, Bath, ShowerHead, SoapDispenserDroplet, Shield,
  VenetianMask, Speech, MessageCircle, Headphones, Volume2, VolumeX, HandHeart, HandHelping,
  BedSingle, BedDouble, Move, MoveUp, MoveDown, MoveLeft, MoveRight, ArrowUpDown,
  RotateCcw, RefreshCcw, Worm, Rat, BugOff, ShieldX, ShieldMinus, BadgePlus,
  BadgeMinus, CircleMinus, HeartCrack, HeartOff, BrainCircuit, BrainCog, Scan, ScanEye,
  ScanHeart, ScanLine, ScanSearch, AudioWaveform, ChartSpline, TrendingUp, TrendingDown, CloudFog,
  Cloudy, EyeClosed, EarOff, MicVocal, MicOff, UtensilsCrossed, Ban, DropletOff,
  CircleSlash, Fingerprint, Sparkles, SunDim, SunSnow, CloudLightning, CloudSun, CircleDot,
  CircleDotDashed, MoveVertical, MoveHorizontal, Webcam, Telescope, SearchCheck, SearchX, Vegan,
  Dessert, Cookie, Coffee, BeerOff, WineOff, PillBottle, HandPlatter, HandMetal,
  HandFist, ThumbsDown, ThumbsUp, CircleOff, OctagonX,
};
